defaults:

  - encoder: config_encoder
  - pretraining: vicreg
  - anomaly_detection: nyc_taxi
  - forecasting: etth1 
  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

  
hydra:  
  output_subdir: null  
  run:  
    dir: .

